#!/bin/bash
timeout=30
if [ ! -z "$3" ]; then
    timeout="$3"
fi
args="--shell --onlyvisible"
for i in $(seq 1 $timeout); do
    idE=()
    idN=()
    if [ ! -z "$1" ]; then
        eval $(xdotool search $args --classname "$1")
        for i in "${WINDOWS[@]}"; do
            idE+=("$i")
        done
    fi
    if [ ! -z "$2" ]; then
        eval $(xdotool search $args --name "$2")
        for i in "${WINDOWS[@]}"; do
            idN+=("$i")
        done
    fi
    unset WINDOWS
    done=0
    id=()
    if [ -z "$1" ]; then
        for i in "${idN[@]}"; do
            id+=("$i")
            done=1
        done
    elif [ -z "$2" ]; then
        for i in "${idE[@]}"; do
            id+=("$i")
            done=1
        done
    else
        for a in "${idE[@]}"; do
            for b in "${idN[@]}"; do
                if [ "$a" == "$b" ]; then
                    id+=("$i")
                    done=1
                    break
                fi
            done
        done
    fi
    if [ $done -eq 1 ]; then
        echo "WINDOWS=(${id[@]})"
        exit 0
    fi
    sleep 1
done
echo "WINDOWS=()"
exit 1
